dev-cafe/cmake-cookbook

- .travis.yml
- Chapter03/recipe-07/cxx-example/CMakeLists.txt
- Chapter03/recipe-09/fortran-example/menu.yml
- Chapter05/recipe-06/fortran-example/menu.yml
- default.nix
- I managed to download and compile HDF5 1.10.1 with `--enable-fortran`
- I updated to CMake 3.10.0
- The Eigen example is broken. `dgemv_` not found. I don't fully understand what's going on
- The HDF5 exampe relying on Fortran2003 fails because Fortran2003 bindings are not available.
All in all, not a lot of progress I am afraid
> HDF5 and CMake

- .travis.yml
HDF5 is still a problem since it takes forever to install and sometimes times out Travis.
> Get the correct CMake version on Linux

- Chapter03/recipe-07/cxx-example/CMakeLists.txt
Mention the fact that to use LAPACK the user needs to have LAPACKE
and that CMake own FindLapack.cmake can't find them...
> Show how to use BLAS (not LAPACK) with Eigen

- .scripts/ci_configure_build_test.py
- .travis.yml
This is simpler and more robust and exposes new failures. See #168.
> Use return code as indicator for success/failure

- .scripts/ci_configure_build_test.py
This fixes the swallowed "building ... OK". No need to skip here since return code is 0 even if there is nothing to build.
> use return code instead of skip predicate; fixes #171

- .scripts/ci_configure_build_test.py
- requirements.txt
The `building ... OK` and `configuring ... OK` strings are now printed in bright green. Hopefully it renders OK on all CI platforms and then it can be helpful when `--verbose` is set.
> Color output from script

- Chapter03/recipe-04/cxx-example/CMakeLists.txt
- Chapter05/recipe-03/cxx-example/CMakeLists.txt
- Chapter05/recipe-04/cxx-example/deps/CMakeLists.txt
This restores the math recipes but I am not sure this is the right solution. I have observed that math target is not linked against blas/lapack. Please double-check whether the solution is really what we want to do here.
> link also the math target agains blas/lapack; fixes #177

- Chapter06/recipe-01/fortran-example/CMakeLists.txt
- Chapter06/recipe-02/fortran-example/CMakeLists.txt
- Chapter06/recipe-03/fortran-example/CMakeLists.txt
This should fix some of the CI issues. In principle necessary. In practice tricky to enforce without checking whether the compiler has the flag or not. Dropping it, for the moment, since all compilers seem to have `iso_c_binding` anyway.
> Do not use -std=f2003 flag

- Chapter04/recipe-02/cxx-example/menu.yml
- Chapter04/recipe-03/cxx-example/menu.yml
- Chapter04/recipe-04/cxx-example/menu.yml
- Chapter06/recipe-07/cxx-example/menu.yml
I forgot this when refactoring for the global menu.yml.
> rm orphaned broken symlinks

- Chapter03/recipe-10/cxx-example/CMakeLists.txt
- Chapter04/recipe-04/cxx-example/CMakeLists.txt
I think that when it's possible you should really prefer the use of imported targets compared to legacy CMake variables definitions for lib, includes, flags etc...
Imported targets convey all what you need in a concise way.
This pull request shows 2 examples of use:
- one for Boost
- one for PkgConfig
both these find modules defines imported target.
> Use imported targets

- chapter-01/recipe-07/cxx-example/CMakeLists.txt
- chapter-01/recipe-08/cxx-example/CMakeLists.txt
- chapter-01/recipe-09/fortran-example/CMakeLists.txt
- chapter-01/recipe-10/cxx-example/CMakeLists.txt
This PR consists of trivial changes plus a more significant one: The foreach recipe has been changed to not use glob but rather list all sources explicitly. The example now shows how to set and query extra compile flags for specific sources. The example shows how to lower optimization on certain sources. This could be done by defining a new target (and this will be discussed in the book) or the way it is demonstrated in the sources.
> Do not show globbing in recipes since this is not a recommended pattern

- chapter-04/recipe-03/cxx-example-3.5/CMakeLists.txt
- chapter-04/recipe-03/cxx-example-3.5/googletest-download.cmake
- chapter-04/recipe-03/cxx-example-3.5/googletest.cmake
- chapter-04/recipe-03/cxx-example-3.5/main.cpp
- chapter-04/recipe-03/cxx-example-3.5/menu.yml
- chapter-04/recipe-03/cxx-example-3.5/sum_integers.cpp
- chapter-04/recipe-03/cxx-example-3.5/sum_integers.hpp
- chapter-04/recipe-03/cxx-example-3.5/test.cpp
- Rewrote the 3.5 recipe following https://crascit.com/2015/07/25/cmake-gtest/
- Added a compact 3.11 version following https://cmake.org/cmake/help/git-stage/module/FetchContent.html
A lot of ugly hardcoding and duct tape is gone.
> refactor gtest recipe; fixes #276

- chapter-02/recipe-03/cxx-example/CMakeLists.txt
- chapter-02/recipe-03/cxx-example/hello-world.cpp
This is a simple alternative suggestion to show that one can use CMake variable value directly
by using it as preprocessor value as well.
This is not really meant to be merged as-is, but may be you'll find a way to show both approaches?
> Less if/endif, use compiler name/id directly

- .appveyor.yml
- chapter-01/recipe-01/fortran-example/menu.yml
- chapter-01/recipe-02/fortran-example/menu.yml
- chapter-01/recipe-03/fortran-example/menu.yml
- chapter-01/recipe-06/fortran-example/menu.yml
- chapter-01/recipe-07/fortran-example/menu.yml
- chapter-01/recipe-09/fortran-example/menu.yml
- chapter-02/recipe-03/fortran-example/menu.yml
- chapter-03/recipe-04/cxx-example/menu.yml
- chapter-03/recipe-05/fortran-example-3.5/menu.yml
- chapter-03/recipe-05/fortran-example/menu.yml
- chapter-03/recipe-06/c-example-3.5/menu.yml
- chapter-03/recipe-06/c-example/menu.yml
- chapter-03/recipe-06/cxx-example/menu.yml
- chapter-03/recipe-08/cxx-example/menu.yml
- chapter-03/recipe-09/c-example-3.5/menu.yml
- chapter-03/recipe-09/c-example/menu.yml
- chapter-03/recipe-09/cxx-uuid-example-3.5/menu.yml
- chapter-03/recipe-09/cxx-uuid-example/menu.yml
- chapter-03/recipe-10/c-example/FindZeroMQ.cmake
- chapter-03/recipe-10/c-example/hwclient.c
- chapter-03/recipe-10/c-example/hwserver.c
- chapter-03/recipe-10/c-example/menu.yml
- chapter-04/recipe-01/cxx-example/menu.yml
- chapter-04/recipe-03/cxx-example-3.5/googletest.cmake
- chapter-04/recipe-03/cxx-example/CMakeLists.txt
- chapter-04/recipe-04/cxx-example/menu.yml
- chapter-09/recipe-04/cxx-example/menu.yml
Mainly fixes the ZeroMQ example (chapter 3, recipe 10) with VS generator.
> Fix ZeroMQ recipe on Visual Studio

- README.md
- contributing/generate-readmes.py
It seems Appveyor keeps URLs under the namespace of the user who enabled the project.
> adjust appveyor badge url; fixes #351

- chapter-05/recipe-04/cxx-example/CMakeLists.txt
- chapter-05/recipe-04/cxx-example/deps/CMakeLists.txt
@TheErk this change solves the problem with code duplication marking files as generated but I do not understand why it works :-) since all sources are now `PRIVATE`. Does this change make any sense? I agree with you that previously this was clunky.
> Avoid code duplication marking files as generated

- .appveyor.yml
- chapter-11/recipe-04/cxx-example/custom.sh
- chapter-11/recipe-05/cxx-example/custom.sh
- testing/dependencies/appveyor/extract.bat
- testing/dependencies/appveyor/install.bat
- testing/dependencies/appveyor/test.bat
`bash` can be called with just `-c` rather than `-lc`. This allows `PATH` exported in `.appveyor.yml` to be preserved and simplify a bit the `custom.sh`. This addresses #389 
@bast this is ready to go and I suggest you squash-merge it.
> Rework invocation of bash in batch scripts

- testing/dependencies/appveyor/anaconda.ps1
- testing/dependencies/travis/anaconda.sh
This downloads and installs Miniconda (latest Python 3 version) rather than full-fledged Anaconda. The build tools are installed as extra packages. Hopefully should reduce build times when caches are invalidated and size of cache. This was inspired by the Docker images used in the conda-forge project: 
https://github.com/conda-forge/docker-images/blob/master/scripts/run_commands#L18-L43
> Install Miniconda and build tools rather than full Anaconda

- .appveyor.yml
Most significant change is that only latest VS is tested. Other changes are to get clearer overview on Appveyor without clicking every test lane.
> Prunes and reorders Appveyor test matrix

- .appveyor.yml
- chapter-03/recipe-03/cxx-example/CMakeLists.txt
- chapter-03/recipe-03/cxx-example/menu.yml
- chapter-03/recipe-08/cxx-example/menu.yml
- chapter-04/recipe-01/cxx-example/menu.yml
- chapter-04/recipe-04/cxx-example/menu.yml
- chapter-09/recipe-03/cxx-example/CMakeLists.txt
- chapter-09/recipe-03/cxx-example/menu.yml
- chapter-09/recipe-04/cxx-example/CMakeLists.txt
- chapter-09/recipe-04/cxx-example/menu.yml
- chapter-09/recipe-05/cxx-example/account/CMakeLists.txt
- chapter-09/recipe-05/cxx-example/menu.yml
- chapter-11/recipe-02/cxx-example/account/CMakeLists.txt
- chapter-11/recipe-02/cxx-example/menu.yml
- testing/collect_tests.py
- testing/dependencies/appveyor/install.bat
- testing/menu.yml
Uses Boost pre-installed on Appveyor and removes some Windows specific flags from `CMakeLists.txt`. This should reduce startup time, especially if the cache has to be regenerated, cache size and cache upload time.
Takes over and completes #432
> Boost on Appveyor. Closes #426 and #427

- chapter-06/recipe-03/cxx-example/generate.py
Generated file primes.hpp is missing std:: prefix before size_t.
Without this modification on my side I get:
```
In file included from /home/enoulard/Research/CMake/cmake-cookbook/chapter-06/recipe-03/cxx-example/example.cpp:1:0:
/home/enoulard/Research/CMake/cmake-cookbook/chapter-06/recipe-03/cxx-example/b/generated/primes.hpp:4:7: error: ‘size_t’ does not name a type
const size_t max_number = 100;
^~~~~~
```
> size_t must be prefix with std::

- chapter-07/recipe-07/cxx-example/external/CMakeLists.txt
- chapter-07/recipe-07/cxx-example/src/evolution/CMakeLists.txt
- chapter-07/recipe-07/cxx-example/src/initial/CMakeLists.txt
- chapter-07/recipe-07/cxx-example/src/io/CMakeLists.txt
- chapter-07/recipe-07/cxx-example/src/parser/CMakeLists.txt
- chapter-07/recipe-08/cxx-example/src/evolution/CMakeLists.txt
- chapter-07/recipe-08/cxx-example/src/initial/CMakeLists.txt
- chapter-07/recipe-08/cxx-example/src/io/CMakeLists.txt
- chapter-07/recipe-08/cxx-example/src/parser/CMakeLists.txt
Some `target_` commands were not indented as per our convention. TC amended already.
> Format CMake

- chapter-10/recipe-01/cxx-example/menu.yml
- chapter-10/recipe-02/cxx-example/menu.yml
- chapter-10/recipe-03/cxx-example/menu.yml
- chapter-10/recipe-04/cxx-example/menu.yml
- chapter-11/recipe-01/cxx-example/menu.yml
- chapter-13/recipe-01/cxx-example/menu.yml
- chapter-13/recipe-02/cxx-example/menu.yml
- chapter-13/recipe-02/fortran-example/menu.yml
This lets `pipenv run python testing/collect_tests.py` not panic when the `local` stanza of the `menu.yml` is executed (e.g. on the Docker image)
@bast Chapter 13 tries to install to `/usr/local` and I wasn't sure how to set the install prefix and location of toolchain. I can adjust the PR aftewards to make it complete.
> Better install prefixes

- .appveyor.yml
this is to hopefull work around a timeout problem
and not use the latest build worker image
> use "Previous Visual Studio 2017" image

- .appveyor.yml
- .travis.yml
- chapter-03/recipe-08/cxx-example/menu.yml
- chapter-04/recipe-01/cxx-example/menu.yml
- chapter-04/recipe-04/cxx-example/menu.yml
- chapter-09/recipe-04/cxx-example/menu.yml
- testing/dependencies/appveyor/boost.bat
- testing/dependencies/appveyor/install.bat
- testing/dependencies/travis/boost.sh
- testing/dependencies/travis/install.sh
Python 3.5 (at least) is a dependency for the recipes, but it seems prepackaged Boost _never_ comes with a Python 3 flavor for easy consumption. I've resorted to building it from scratch for these cases. The artifacts are cached so that is shouldn't take too long for the builds to go through.
Fixes #480 on Travis GNU/Linux, Travis macOS, and Appveyor with Visual Studio.
P.S.: An isolated example is here: https://github.com/robertodr/build-boost-on-ci ([Travis](https://travis-ci.org/robertodr/build-boost-on-ci) and [Appveyor](https://ci.appveyor.com/project/robertodr/build-boost-on-ci))
P.S.: I couldn't got for 1.67 on Travis GNU/Linux because CMake 3.5.2 doesn't know about it and it would invalidate the use of imported targets.
> Boost set up

- .mailmap
- AUTHORS.md
Does what it says on the tin. The list in `AUTHORS.md` was generated using `git shortlog -sn`, so authors are ordered by number of commits. Which also happens to be alphabetic order on surnames!
> Add AUTHORS.md and .mailmap

- .envrc
- Pipfile.lock
- chapter-11/recipe-02/cxx-example/custom.sh
Does what is says on the tin. The security warning is the one issued by GitHub relating to the `requests` Python library.
> Update .envrc, fix security warning
