to-triage/strong-types/Addable.hpp
to-triage/strong-types/CMakeLists.txt
to-triage/strong-types/CRTP.hpp
to-triage/strong-types/Incrementable.hpp
to-triage/strong-types/Multiplicable.hpp
to-triage/strong-types/NamedType.hpp
to-triage/strong-types/Printable.hpp
to-triage/strong-types/README.md
to-triage/strong-types/strong-types.cpp

This is just code that we might use in C++ recipes.

Add source code for possible recipe

---

.travis.yml

- Always install Ninja
- Always install GFortran, use references in YAML

Fix Travis Linux builds

---

Chapter05/README.md
Chapter05/recipe-02/cxx-example/CMakeLists.txt
Chapter05/recipe-02/cxx-example/Report.hpp.in
Chapter05/recipe-02/cxx-example/menu.yml
Chapter05/recipe-02/cxx-example/pure-embedding.cpp
Chapter05/recipe-02/cxx-example/use_numpy.py

Add chapter 5, recipe 2

---

Chapter03/recipe-09/fortran-example/CMakeLists.txt

Set `INCLUDE_DIRECTORIES` and `LINK_LIBRARIES` for `try_compile`. The test always fails otherwise...

Fix chapter 3, recipe 9

---

Chapter05/recipe-08/c-example/menu.yml
Chapter05/recipe-09/cxx-example/menu.yml

Add missing menu files

---

.scripts/ci_configure_build_test.py
.scripts/report_versions.sh
.travis.yml

- At least one build works now: Ninja on Linux.
- Linux and Unix Makefiles still fails because of #147.
- HDF5 problem seems gone (compiling on 2 cores without optimization).
- Mac cannot find gfortran. I have no idea why since it should be part of gcc which is installed with brew.

Debugging Travis

---

.travis.yml
Chapter01/recipe-01/fortran-example/menu.yml
Chapter01/recipe-02/fortran-example/menu.yml
Chapter01/recipe-03/fortran-example/menu.yml
Chapter01/recipe-07/fortran-example/menu.yml
Chapter01/recipe-08/fortran-example/menu.yml
Chapter01/recipe-10/fortran-example/menu.yml
Chapter02/recipe-03/fortran-example/menu.yml
Chapter03/recipe-01/fortran-example/menu.yml
Chapter03/recipe-05/fortran-example/menu.yml
Chapter03/recipe-09/fortran-example/menu.yml
Chapter05/recipe-06/fortran-example/menu.yml

Picks up where @bast left off with #148

More Travis debugging

---

.envrc
.scripts/ci_configure_build_test.py
.scripts/install_deps.sh
.travis.yml
Chapter03/recipe-07/cxx-example/menu.yml
Chapter03/recipe-09/fortran-example/menu.yml
Chapter05/recipe-02/README.md
Chapter05/recipe-03/README.md
Chapter05/recipe-04/README.md
Chapter05/recipe-05/README.md
Chapter05/recipe-06/README.md
Chapter05/recipe-06/fortran-example/menu.yml
Chapter05/recipe-07/README.md
Chapter05/recipe-08/README.md
Chapter05/recipe-08/c-example/menu.yml
Chapter05/recipe-09/README.md
requirements.txt

This speeds up builds significantly, since we won't have to download/build the dependencies all the time. It doesn't work on Mac OS X currently, so probably hold off merging until I have the patience to troubleshoot it. I have also reworked the way the script handles arguments and now we can ask for verbose builds. You might want to cherry-pick that commit before this one gets merged.

Make use of caching on Travis

---

README.md

Do you think it is worth while to explain the style a bit in the book or is this overkill? If you think this should be done, please keep the PR open until I write a paragraph or two in the book.

Rearrange README and document coding style

---

.scripts/ci_configure_build_test.py
Chapter06/recipe-01/README.md
Chapter06/recipe-02/README.md
Chapter06/recipe-02/fortran-example/CMakeLists.txt
Chapter06/recipe-03/README.md
Chapter06/recipe-03/fortran-example/CMakeLists.txt
Chapter06/recipe-03/fortran-example/configurator.py
Chapter06/recipe-03/fortran-example/hello-world.f90
Chapter06/recipe-03/fortran-example/menu.yml
Chapter06/recipe-03/fortran-example/print_info.c.in

This recipe shows how to use Python to generate code. With this example I want to show how one can have an intermediate code generation layer that can be shared among different build systems for the same code.

Add final recipe in Chapter 6

---

.scripts/install_deps.sh

references:
https://github.com/Homebrew/homebrew-core/issues/21172 and https://github.com/JuliaSmoothOptimizers/Optimize.jl/commit/060c6c9a2cf2d91c41a3bd2dd7f49d293fc377c1

restore install_deps.sh on Travis OS X; fixes #182

---

Chapter06/recipe-03/cxx-example/CMakeLists.txt

I did it "wrong" all these years, now I understood how to do it simpler.

simplify recipe, a custom target is not needed

---

Chapter06/recipe-07/cxx-example/CMakeLists.txt

reformat and simplify custom command

---

Chapter02/README.md
Chapter02/recipe-06/README.md
Chapter02/recipe-06/cxx-example/CMakeLists.txt
Chapter02/recipe-06/cxx-example/linear-algebra.cpp
Chapter02/recipe-06/cxx-example/menu.yml

Ready to go. TC-ing in progress.

Add chapter 2, recipe 6

---

Chapter02/README.md
Chapter02/recipe-05/README.md
Chapter02/recipe-05/cxx-example/CMakeLists.txt
Chapter02/recipe-05/cxx-example/config.h.in
Chapter02/recipe-05/cxx-example/processor-info.cpp

Starting working on the recipe "Discovering the host processor instruction set".

Chapter 2 additions

---

Chapter01/recipe-01/c-example/hello-world.c
Chapter01/recipe-02/c-example/hello-world.c
Chapter01/recipe-06/c-example/hello-world.c
Chapter01/recipe-07/c-example/hello-world.c
Chapter03/recipe-02/c-example/hello-embedded-python2.c
Chapter03/recipe-02/c-example/hello-embedded-python3.c
Chapter03/recipe-06/c-example/hello-mpi.c
Chapter05/recipe-08/c-example/test-uuid.c

Well, almost all. I left files written by others unchanged.

clang-format all files

---

.travis.yml
dependencies/install_dependencies.sh

Cache anaconda on Travis

---

README.md
contributing/README.md

Let's slowly start to get real.

mv contributing guide to own readme, clean up readme

---

.travis.yml

once the cache is rebuilt, we reactivate all chapters again

limit testing to chapter 1 to rebuild dependency cache

---

.travis.yml

This is because I will want to do at least one recipe which uses 3.11.

Travis Linux test under CMake 3.11.0

---

chapter-07/recipe-02/cxx-example/src/CMakeLists.txt

add comment why target_include_directories is kept

---

chapter-04/recipe-01/cxx-example/main.cpp
chapter-04/recipe-01/cxx-example/sum_integers.cpp
chapter-04/recipe-01/cxx-example/sum_integers.hpp
chapter-04/recipe-01/cxx-example/test.cpp
chapter-04/recipe-02/cxx-example/sum_integers.hpp
chapter-04/recipe-02/cxx-example/test.cpp
chapter-04/recipe-03/cxx-example/sum_integers.hpp
chapter-04/recipe-03/cxx-example/test.cpp
chapter-04/recipe-04/cxx-example/sum_integers.hpp
chapter-04/recipe-04/cxx-example/test.cpp
chapter-04/recipe-05/cxx-example/leaky_implementation.cpp
chapter-04/recipe-05/cxx-example/test.cpp

This is not really round two refactoring but I will reuse some of this for CDash examples and wanted to clean things up first.

refactor chapter 4

---

chapter-15/recipe-04/cxx-example/CMakeLists.txt

initially it was 3.9 because I started with omp

lower recipe requirement to 3.5

---

.travis.yml
README.md
chapter-14/README.md
chapter-14/recipe-01/README.md
chapter-14/recipe-01/cxx-example/CMakeLists.txt
chapter-14/recipe-01/cxx-example/hello-world.cpp
chapter-14/recipe-01/cxx-example/menu.yml
chapter-14/recipe-01/title.txt
chapter-14/recipe-02/README.md
chapter-14/recipe-02/cxx-example/CMakeLists.txt
chapter-14/recipe-02/cxx-example/example.cpp
chapter-14/recipe-02/cxx-example/menu.yml
chapter-14/recipe-02/fortran-example/CMakeLists.txt
chapter-14/recipe-02/fortran-example/example.f90
chapter-14/recipe-02/fortran-example/menu.yml
chapter-14/recipe-02/title.txt
chapter-14/title.txt
chapter-14/toolchain-travis-linux.cmake

This starts with a refactor of OpenMP examples since I will reuse them in chapter 14.
Planning for 3-4 recipes:
- Visual studio
- Possibly Ninja
- Simple Linux -> Windows cross-compilation
- Linux -> Windows cross-compilation with OpenMP

Chapter 14

---

.drone.yml
.travis.yml
chapter-07/recipe-05/fortran-example/external/upstream/hdf5/CMakeLists.txt
default.nix
testing/dependencies/install_dependencies.sh

Expunge installation of HDF5

---

chapter-01/recipe-10/cxx-example/menu.yml
chapter-14/recipe-01/cxx-example/menu.yml
chapter-14/recipe-02/cxx-example/menu.yml
chapter-14/recipe-02/fortran-example/menu.yml
testing/menu.yml

Only red on Travis is for GTest recipe with CMake 3.5 :fireworks:

Travis fixes

---

README.md
chapter-05/README.md
chapter-05/recipe-01/cxx-example/linear-algebra.cpp
chapter-05/recipe-02/cxx-example/CMakeLists.txt
chapter-05/recipe-03/cxx-example/linear-algebra.cpp
chapter-05/recipe-03/cxx-example/menu.yml
chapter-05/recipe-04/cxx-example/linear-algebra.cpp
chapter-05/recipe-04/cxx-example/menu.yml
chapter-05/recipe-05/cxx-example/CMakeLists.txt
chapter-05/recipe-06/README.md
chapter-05/recipe-06/cxx-example-3.5/CMakeLists.txt
chapter-05/recipe-06/cxx-example/CMakeLists.txt
chapter-05/recipe-06/title.txt
chapter-05/recipe-08/c-example-3.5/CMakeLists.txt
chapter-05/recipe-08/c-example-3.5/menu.yml
chapter-05/recipe-08/c-example/CMakeLists.txt
chapter-05/recipe-08/c-example/menu.yml
chapter-05/recipe-09/cxx-example/menu.yml
chapter-07/recipe-04/cxx-example-3.5/src/linear-algebra.cpp
chapter-07/recipe-04/cxx-example/src/linear-algebra.cpp
chapter-09/recipe-02/cxx-example/src/linear-algebra.cpp
testing/dependencies/appveyor/test.bat

Address comments from editor and reviewer. Plus test chapter 5 on appveyor. Since there was some appveyor work included, I based this one off #341 rather than current `master`. I suggest #345 is pulled in, then #341, then this one (with rebases in between as necessary)

Chapter 5: address comments from editor and reviewer 

---

.appveyor.yml
.github/CONTRIBUTING.md
LICENSE
README.md
chapter-11/recipe-01/cxx-example/LICENSE
chapter-11/recipe-02/cxx-example/LICENSE
chapter-11/recipe-03/cxx-example/LICENSE
chapter-11/recipe-04/cxx-example/LICENSE
chapter-11/recipe-05/cxx-example/LICENSE
contributing/generate-readmes.py

Travis moved on its own. I have enabled the new repo on Appveyor.
I haven't done anything on the Drone side. Can you please update Drone testing Roberto before merging this change?

adjust badges and URLs to point to new place; fixes #348

---

.appveyor.yml
chapter-02/recipe-06/cxx-example/menu.yml
chapter-03/recipe-07/cxx-example-3.5/menu.yml
chapter-03/recipe-07/cxx-example/menu.yml
chapter-03/recipe-10/c-example/FindZeroMQ.cmake
testing/dependencies/appveyor/install.bat

Cache packages installed using VcPkg, so that we don't need to wait 50+ minutes for Appveyor to run CI.

Get Appveyor caching right

---

chapter-05/recipe-01/cxx-example/CMakeLists.txt
chapter-05/recipe-02/cxx-example/CMakeLists.txt
chapter-05/recipe-03/cxx-example/CMakeLists.txt
chapter-05/recipe-05/cxx-example/CMakeLists.txt
chapter-05/recipe-08/c-example/CMakeLists.txt

But please check the commit where I removed C lang.

Chapter 5: minor formatting and consistency

---

chapter-03/recipe-10/c-example/hwserver.c
chapter-04/recipe-01/cxx-example/main.cpp
chapter-05/recipe-06/cxx-example/taskloop.cpp

ran clang-format on all our sources

---

chapter-01/recipe-06/README.md
chapter-01/recipe-07/README.md
chapter-02/recipe-01/README.md

Trivial change. Forgot to run the update script in #376.

update readmes after some recipes language-merged

---

chapter-04/recipe-01/cxx-example/CMakeLists.txt
chapter-04/recipe-01/cxx-example/test.py
chapter-04/recipe-01/cxx-example/test.sh
chapter-04/recipe-08/using-cost-example/test
chapter-04/recipe-08/using-cost-example/test/a.py
chapter-04/recipe-08/using-cost-example/test/b.py
chapter-04/recipe-08/using-cost-example/test/c.py
chapter-04/recipe-08/using-cost-example/test/d.py
chapter-04/recipe-08/using-cost-example/test/e.py
chapter-04/recipe-08/using-cost-example/test/f.py
chapter-04/recipe-08/using-cost-example/test/g.py
chapter-04/recipe-08/using-cost-example/test/h.py
chapter-04/recipe-08/using-cost-example/test/i.py
chapter-04/recipe-08/using-cost-example/test/j.py

Hopefully - let us consult the test result before merging.

Fixes Appveyor issues in chapter 4

---

chapter-04/recipe-01/cxx-example/test.sh
chapter-04/recipe-02/cxx-example/CMakeLists.txt
chapter-04/recipe-02/cxx-example/test.cpp
chapter-04/recipe-03/cxx-example-3.5/CMakeLists.txt
chapter-04/recipe-03/cxx-example/CMakeLists.txt
chapter-04/recipe-04/cxx-example/CMakeLists.txt
chapter-04/recipe-05/cxx-example/CMakeLists.txt
chapter-04/recipe-09/example/CMakeLists.txt
chapter-04/recipe-10/example/CMakeLists.txt

Chapter 4 cleanup

---

chapter-08/recipe-06/cxx-example/external/upstream/message/CMakeLists.txt
chapter-08/recipe-06/cxx-example/src/CMakeLists.txt

fix target in 8/6 - see #403

---

.appveyor.yml
chapter-12/recipe-02/cxx-example/docs/conf.py.in
chapter-12/recipe-03/cxx-example/docs/conf.py.in
testing/dependencies/appveyor/install.bat

Restore chapter 12 tests

---

.appveyor.yml

Filing this PR just to see the effect.

use uniform image; fixes #417

---

chapter-11/recipe-01/cxx-example/CMakeLists.txt
chapter-11/recipe-01/cxx-example/cmake/messageConfig.cmake.in
chapter-11/recipe-01/cxx-example/src/CMakeLists.txt
chapter-11/recipe-01/cxx-example/tests/CMakeLists.txt
chapter-11/recipe-01/cxx-example/tests/use_target/CMakeLists.txt

Now it builds on top of chapter 10, recipe 3 and this is mentioned in TC.

Last minute update to chapter 11, recipe 1

---

chapter-03/recipe-09/README.md
chapter-11/recipe-03/README.md

Trivial change after running the readme assembling script.

update toc readmes

---

README.md
chapter-01/recipe-01/c-example/menu.yml
chapter-01/recipe-01/cxx-example/menu.yml
chapter-01/recipe-02/c-example/menu.yml
chapter-01/recipe-02/cxx-example/menu.yml
chapter-01/recipe-03/cxx-example/menu.yml
chapter-01/recipe-03/cxx-objlib-example/menu.yml
chapter-01/recipe-04/cxx-example/menu.yml
chapter-01/recipe-05/cxx-example/menu.yml
chapter-01/recipe-06/example/menu.yml
chapter-01/recipe-07/example/menu.yml
chapter-01/recipe-10/cxx-example/menu.yml
contributing/generate-readmes.py

CircleCI follow up

---

README.md
chapter-15/README.md
contributing/generate-readmes.py

This should have no effect on CI since only READMEs are changing.

provide context for chapter 15; closes #394

---

chapter-01/recipe-03/cxx-objlib-example/CMakeLists.txt

Ready to go and TC is in sync.

micro-change in code comment to avoid strange line wrap

---

chapter-03/recipe-05/cxx-example/CMakeLists.txt
chapter-03/recipe-05/fortran-example/CMakeLists.txt

Ready to go and TC is in sync.

3/5 microedit: adjust formatting

---

README.md
chapter-05/README.md
chapter-05/recipe-03/README.md
chapter-05/recipe-03/title.txt
chapter-05/recipe-04/README.md
chapter-05/recipe-04/title.txt
chapter-05/recipe-05/fortran-example/static-size.py

- TC is in sync
- ready to go but please still check that you agree to the recipe title changes

Chapter 5 sweep

---

README.md
chapter-04/README.md
chapter-04/recipe-01/README.md
chapter-04/recipe-01/cxx-example/test.py
chapter-04/recipe-01/title.txt
chapter-04/recipe-02/README.md
chapter-04/recipe-02/title.txt
chapter-04/recipe-03/README.md
chapter-04/recipe-03/title.txt
chapter-04/recipe-04/README.md
chapter-04/recipe-04/title.txt
chapter-04/recipe-05/README.md
chapter-04/recipe-05/title.txt

WIP, might add more to the PR. Just to get the testing feedback in time ...

[WIP] chapter 4 micro-cleanup

---

README.md
chapter-06/README.md
chapter-06/recipe-01/README.md
chapter-06/recipe-01/title.txt
chapter-06/recipe-02/README.md
chapter-06/recipe-02/abstract.md
chapter-06/recipe-02/fortran-c-example/CMakeLists.txt
chapter-06/recipe-02/title.txt
chapter-06/recipe-03/README.md
chapter-06/recipe-03/title.txt
chapter-06/recipe-04/c-example/CMakeLists.txt
chapter-06/recipe-05/cxx-example/CMakeLists.txt
chapter-06/recipe-06/README.md
chapter-06/recipe-06/cxx-example/CMakeLists.txt
chapter-06/recipe-06/title.txt
chapter-06/recipe-07/README.md
chapter-06/recipe-07/cxx-example/CMakeLists.txt
chapter-06/recipe-07/cxx-example/git-hash.cmake
chapter-06/recipe-07/title.txt

- TC is in sync and ready to go once CI agrees.

Chapter 6 sweep

---

chapter-11/recipe-05/cxx-example/conda-recipe/meta.yaml

WIP but now want to get a change in the conda recipe tested. Not yet in the book.

Chapter 11

---

chapter-14/recipe-03/fortran-example/CMakeLists.txt
chapter-14/recipe-03/fortran-example/src/CMakeLists.txt

Does what it says on the tin. Removes some copy-paste residues and fixes flags. TC didn't need any syncing.

Adjust fortran ASan example

---

default.nix

Cleans up `default.nix` a little bit.

Prune default.nix

---

chapter-13/recipe-01/cxx-example/CMakeLists.txt
chapter-13/recipe-02/cxx-example/CMakeLists.txt
chapter-13/recipe-02/fortran-example/CMakeLists.txt

TC in sync and ready to go.
Figures will come in a separate PR.

more consistent formatting

---

testing/README.md
testing/menu.yml

I don't think verbose should be the default. Do you agree?

more silent output from local testing

---

.appveyor.yml
default.nix

Does what it says on the tin. We should now have the precious cache.

Reinstate all tests on Appveyor

---

README.md
chapter-04/README.md
chapter-04/recipe-03/README.md
chapter-04/recipe-03/title.txt
chapter-05/recipe-04/cxx-example/deps/CMakeLists.txt
chapter-08/README.md
chapter-08/recipe-04/README.md
chapter-08/recipe-04/title.txt
chapter-10/README.md
chapter-10/recipe-04/README.md
chapter-10/recipe-04/title.txt

Minor pre-final fixes

---

README.md
chapter-03/README.md
chapter-03/recipe-09/README.md
chapter-03/recipe-09/title.txt
chapter-05/README.md
chapter-05/recipe-02/README.md
chapter-05/recipe-02/title.txt
chapter-05/recipe-03/README.md
chapter-05/recipe-03/title.txt
chapter-05/recipe-04/README.md
chapter-05/recipe-04/title.txt
chapter-05/recipe-05/README.md
chapter-05/recipe-05/title.txt
chapter-06/recipe-02/README.md
chapter-06/recipe-02/abstract.md
chapter-07/README.md
chapter-07/recipe-07/README.md
chapter-07/recipe-07/title.txt
chapter-07/recipe-08/README.md
chapter-07/recipe-08/title.txt

Minor fixes in title formatting

---

chapter-02/recipe-01/abstract.md
chapter-02/recipe-02/abstract.md
chapter-02/recipe-03/README.md
chapter-02/recipe-03/abstract.md
chapter-02/recipe-04/abstract.md
chapter-02/recipe-05/abstract.md
chapter-02/recipe-06/abstract.md
chapter-04/recipe-01/abstract.md
chapter-04/recipe-02/abstract.md
chapter-04/recipe-03/abstract.md
chapter-04/recipe-04/abstract.md
chapter-04/recipe-05/abstract.md
chapter-04/recipe-06/abstract.md
chapter-04/recipe-07/abstract.md
chapter-04/recipe-08/abstract.md
chapter-04/recipe-09/abstract.md
chapter-04/recipe-10/abstract.md
chapter-12/recipe-01/abstract.md
chapter-12/recipe-02/abstract.md
chapter-12/recipe-03/abstract.md
chapter-14/recipe-01/README.md
chapter-14/recipe-01/abstract.md
chapter-14/recipe-02/abstract.md
chapter-14/recipe-03/abstract.md
chapter-14/recipe-04/abstract.md

- Rest of chapters hopefully tonight.
- Ready to go.

Abstracts for chapters 2, 4, 12, and 14.

---

README.md
contributing/generate-readmes.py

Add link to publisher in `README.md`

Add link to publisher

---

chapter-06/recipe-01/abstract.md
chapter-06/recipe-02/README.md
chapter-06/recipe-02/abstract.md
chapter-06/recipe-03/README.md
chapter-06/recipe-03/abstract.md
chapter-06/recipe-04/abstract.md
chapter-06/recipe-05/README.md
chapter-06/recipe-05/abstract.md
chapter-06/recipe-06/abstract.md
chapter-06/recipe-07/README.md
chapter-06/recipe-07/abstract.md
chapter-08/recipe-01/README.md
chapter-08/recipe-01/abstract.md
chapter-08/recipe-02/abstract.md
chapter-08/recipe-03/abstract.md
chapter-08/recipe-04/README.md
chapter-08/recipe-04/abstract.md
chapter-08/recipe-05/README.md
chapter-08/recipe-05/abstract.md
chapter-10/recipe-01/abstract.md
chapter-10/recipe-02/abstract.md
chapter-10/recipe-03/abstract.md
chapter-10/recipe-04/abstract.md

Ready to go but possibly too brief?

Abstracts for chapters 6, 8, and 10
